# change the followings to match your Github username and repo name
baseurl: "/website" # the name of your github repo
url: "https://joesalowitz.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Joe Salowitz | CXO at Lead Scout"
description: Joe Salowitz is the co-founder and head of product design and strategy at Lead Scout. Over 15 years of experience bringing products to market.

# color theme for links
theme-color: green # indigo|yellow|pink|green|stone|

# homepage information
author: Joe Salowitz
author-bio: CXO at Lead Scout  # change to false to hide
author-image: 279.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Work
  permalink: makes
- text: Writing
  permalink: writes

# use false to turn off any social media links
twitter: https://twitter.com/joesalowitz
facebook: https://facebook.com/joesalowitz
instagram: https://instagram.com/jsalowitz
github: https://github.com/joesalowitz
linkedin: https://linkedin.com/in/joesalowitz
medium: https://medium.com/joesalowitz
google-scholar: false
email: false

# footer information
footer-msg: "*Designer stuff* This site was built with this and that and the other thing. Tailwind, Jekyll, Visual Studio, Markdown, Github, etc."
footer-msg-link: /

# google analytics
google-analytics: G-1231231234

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
    - jekyll-contentblocks
